# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml



trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: BuildAKSTerraform
  jobs:
  - job: BuildAKSTerraform
    steps:
    - task: InstallSSHKey@0
      inputs:
        knownHostsEntry: 
        sshPublicKey: '$(SSH-KEY-PUB)'
        sshKeySecureFile: 
      env:
        SSH-KEY-PUB: $(ssh-key-pub)
    - task: TerraformTaskV2@2
      displayName: Terraform init 
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-aks-k8s/'
        backendServiceArm: 'Essai gratuit(e66d562c-9e74-47b7-a847-c6d192e8b54b)'
        backendAzureRmResourceGroupName: 'TFRresourceGroup'
        backendAzureRmStorageAccountName: 'newdavblob'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'terraform.tfstate'
    - task: TerraformTaskV2@2
      displayName: Terraform validate
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-aks-k8s/'
    - task: TerraformTaskV2@2
      displayName: Terraform plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-aks-k8s/'
        environmentServiceNameAzureRM: 'Essai gratuit(e66d562c-9e74-47b7-a847-c6d192e8b54b)'
      env:
        TF_VAR_client_id: $(service-principal-appid)
        TF_VAR_client_secret: $(service-principal-password)
    
    