---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: stage-deployment
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./k8s
  prune: true
  sourceRef:
    kind: GitRepository
    name: staging
  validation: client

