adminUser: admin
adminPassword: admin

sidecar:
  datasources:
    enabled: true
    label: grafana_datasource

service:
  type: NodePort
  nodePort: 8081

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: default
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        editable: false
        options:
          path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    node-exporter:
      gnetId: 1860
      revision: 14
      datasource: Prometheus
    prometheus-stats:
      gnetId: 2
      revision: 2
      dataSource: Prometheus
