apiVersion: v1
kind: Namespace
metadata:
  name:  kube-monitoring


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-grafana-datasource
  namespace: kube-monitoring
  labels:
    grafana_datasource: '1'
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
     - name: Prometheus
       type: prometheus
       access: proxy
       orgId: 1
       url: http://prometheus-server.monitoring.svc.cluster.local
